version: "3"

volumes:
  postgres_data:
      driver: local
      
services:
  postgres:
    image: postgres:11
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: ${KEYCLOAK_DB}
        POSTGRES_USER: sa
        POSTGRES_PASSWORD: ${SA_PASSWORD}
  keycloak:    
    image: jboss/keycloak:7.0.0
    container_name: kc
    depends_on:
        - postgres
    ports:
        - "${KEYCLOAK_HTTP_PORT}:8080"
    volumes:
        - "./keycloak:/opt/jboss/import"     
    environment:
        - DB_VENDOR=POSTGRES
        - DB_SCHEMA=public
        - KEYCLOAK_USER=${KEYCLOAK_USER}
        - KEYCLOAK_PASSWORD=${KEYCLOAK_PWD}                       
        - DB_USER=sa
        - DB_PASSWORD=${SA_PASSWORD}
        - DB_ADDR=postgres
        - DB_DATABASE=${KEYCLOAK_DB}
        - KEYCLOAK_IMPORT=import/siscc-realm.json